Template_Header = "";
Template_Wrapper = "<div id = "wrapper">";
Template_Container_NO_JS = "<div id = 'content' style=\"display: none;\">";
Template_Container_JS = "<div id = 'content' style=\"display: none;\">";
Table_Definition = "<table id = 'filetable'>";
Table_Definition_Additional = "##def<th></th><th>##name</th>";
Uploaded = true;
Uploaded_template_header = "<th>##uploaded</th>";
Copy_Hint = "<h3 id ='copyhint'>##Paste_Description <a href = 'index.php?module=list'>##Abort</a></h3><br>";
Size = true;
Size_template_header = "<th>##size</th>";
Actions = true;
Actions_template_header = "<th>##actions</th>";
Status = true;
Status_template_header = "<th>##status</th>";
Actions_template_file = "<td class =  'actions' ><a class = 'delete' title = '##delete' href ='index.php?module=delete&file=##hash'><img  src = './Images/page_delete.png'></a><a class = 'delete' title = '##cut' href ='index.php?module=list&move=true&file=##hash'><img  src = './Images/cut_red.png'></a><a class = 'delete' title = '##copy' href ='index.php?module=list&copy=true&file=##hash'><img  src = './Images/page_copy.png'></a><a class = 'delete' title = '##rename' href ='index.php?module=rename&file=##hash'><img  src = './Images/textfield_rename.png'></a><a class = 'delete' title = '##download' href ='index.php?module=download&file=##hash'><img  src = './Images/arrow_down.png'></a>";
Actions_template_folder = "<td class =  'actions' ><a class = 'delete' title = '##delete' href ='index.php?module=delete&dir=##filename'><img  src = './Images/folder_delete.png'></a><a class = 'delete' title = '##cut' href ='index.php?module=list&move=true&source=##filename&old_root=##directory'><img  src = './Images/cut_red.png'></a><a class = 'delete' title = '##copy' href = 'index.php?module=list&copy=true&source=##filename&old_root=##directory'><img src= './Images/page_copy.png'></a><a class = 'delete' title = '##rename' href ='index.php?module=rename&source=##displayname&old_root=##currentdir'><img  src = './Images/textfield_rename.png'></a><a class = 'delete' title = '##download' href ='index.php?module=zip&dir=##displayname'><img  src = './Images/arrow_down.png'></a>";
Status_template_shared = "<a class = 'shared' href = 'index.php?module=share&file=##hash&delete=true'>##shared</a>";
Status_template_share = "<a href = 'index.php?module=share&file=##hash&new=true'>##share</a>";
Table_Item_Definition = "<tr class = 'filetype##suffix'>";
Table_Item_template = "<td><img  src='##imagepath'></td><td   id = '##hash' >##dirlink</td><td>##uploaded</td><td class ='size'>##size</td>";
Table_Item_Search_template = "<td class =  'actions' ><a class = 'delete' title = '##open' href ='index.php?##modulelink'><img  src = './Images/door_open.png'></a></td>";
Table_File_Definition = "<tr class = 'filetype$suffix'>";
Table_File_template = "<td><img src='##imagepath'></td><td  id = '##hash' ><a class = 'filelink' title = '##directory##displayname' href = 'index.php?module=file&file=##hash'>##croppeddisplayname</a></td><td>##uploaded</td><td class ='size'>##size</td>";
Share_Link = "<a href ='##link'><img src = './Images/link_go.png' alt='link' title='##Share_Link'></a>";
Move_file= "<tr class = 'filetype##suffix'><td><img src='./Images/mimetypes/folder.png'></td><td><a class = 'filelink' href = 'index.php?module=move&dir=##currentdir&file=##fileToCopyOrToMove'>##Paste_Home</a></td><td></td><td></td><td class =  'actions' ></td><td></td></tr>";
Move_folder="<tr class = 'filetype##suffix'><td><img src='./Images/mimetypes/folder.png'></td><td><a class = 'filelink' href = 'index.php?module=move&target=##currentdir&source=##fileToCopyOrToMove&old_root=##old_root'>##Paste_Home</a></td><td></td><td></td><td class =  'actions' ></td><td></td></tr>";
Copy_file= "<tr class = 'filetype##suffix'><td><img src='./Images/mimetypes/folder.png'></td><td><a class = 'filelink' href = 'index.php?module=copy&dir=##currentdir&file=##fileToCopyOrToMove'>##Paste_Home</a></td><td></td><td></td><td class =  'actions' ></td><td></td></tr>";
Copy_folder="<tr class = 'filetype$suffix'><td><img src='./Images/mimetypes/folder.png'></td><td><a class = 'filelink' href = 'index.php?module=copy&target=##currentdir&source=##fileToCopyOrToMove&old_root=##old_root'>##Paste_Home</a></td><td></td><td></td><td class =  'actions' ></td><td></td></tr>";
Delete_folder = "<a class = 'diractions' href ='index.php?module=delete&dir=##currentdir'>##Delete_Folder</a>";
